sudo: required

language: ruby

service:
  - docker

before install:
  - docker build -t mrzeznic/simplewabapp .
  - docker ps -a
  - docker run -p 8080:8080 mrzeznic/simplewebapp run

script:
  - bundle exec rake test